/**
 * @file change-request.entity.ts
 * @description Entity enum definitions
 */

export enum ChangeType { DESIGN = 'DESIGN', PROCESS = 'PROCESS', MATERIAL = 'MATERIAL', SUPPLIER = 'SUPPLIER', SPECIFICATION = 'SPECIFICATION', OTHER = 'OTHER' }
export enum ChangeStatus { DRAFT = 'DRAFT', REQUESTED = 'REQUESTED', SUBMITTED = 'SUBMITTED', REVIEWING = 'REVIEWING', APPROVED = 'APPROVED', REJECTED = 'REJECTED', IMPLEMENTING = 'IMPLEMENTING', IMPLEMENTED = 'IMPLEMENTED', COMPLETED = 'COMPLETED', CLOSED = 'CLOSED' }
