-- CreateEnum
CREATE TYPE "InspectionType" AS ENUM ('INCOMING', 'IN_PROCESS', 'FINAL', 'PATROL', 'PERIODIC');

-- CreateEnum
CREATE TYPE "InspectionJudgment" AS ENUM ('PASS', 'FAIL', 'CONDITIONAL');

-- CreateEnum
CREATE TYPE "InspectionStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ResultJudgment" AS ENUM ('PASS', 'FAIL', 'NA');

-- CreateEnum
CREATE TYPE "NcrStatus" AS ENUM ('DRAFT', 'OPEN', 'IN_PROGRESS', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "DefectType" AS ENUM ('DIMENSIONAL', 'VISUAL', 'FUNCTIONAL', 'MATERIAL', 'CONTAMINATION', 'OTHER');

-- CreateEnum
CREATE TYPE "NcrSource" AS ENUM ('INCOMING', 'IN_PROCESS', 'FINAL', 'CUSTOMER', 'FIELD');

-- CreateEnum
CREATE TYPE "DispositionType" AS ENUM ('USE_AS_IS', 'REWORK', 'REPAIR', 'SCRAP', 'RETURN_TO_SUPPLIER', 'SORT');

-- CreateEnum
CREATE TYPE "ReviewStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'DEFERRED');

-- CreateEnum
CREATE TYPE "ApqpProjectStatus" AS ENUM ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ApqpPhaseType" AS ENUM ('PHASE1_PLANNING', 'PHASE2_DESIGN', 'PHASE3_PROCESS', 'PHASE4_VALIDATION', 'PHASE5_PRODUCTION');

-- CreateEnum
CREATE TYPE "ApqpPhaseStatus" AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD');

-- CreateEnum
CREATE TYPE "DeliverableStatus" AS ENUM ('NOT_SUBMITTED', 'SUBMITTED', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "PpapDocumentType" AS ENUM ('DESIGN_RECORD', 'ENGINEERING_CHANGE', 'CUSTOMER_APPROVAL', 'DFMEA', 'PROCESS_FLOW', 'PFMEA', 'CONTROL_PLAN', 'MSA', 'DIMENSIONAL', 'MATERIAL_TEST', 'PERFORMANCE_TEST', 'QUALIFIED_LAB', 'APPEARANCE_APPROVAL', 'SAMPLE_PRODUCT', 'MASTER_SAMPLE', 'CHECKING_AIDS', 'CUSTOMER_SPECIFIC', 'PSW');

-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('NOT_SUBMITTED', 'SUBMITTED', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "PpapStatus" AS ENUM ('NOT_SUBMITTED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'INTERIM_APPROVED');

-- CreateEnum
CREATE TYPE "ApprovalAction" AS ENUM ('SUBMIT', 'APPROVE', 'REJECT', 'RESUBMIT', 'CANCEL');

-- CreateEnum
CREATE TYPE "TestCategory" AS ENUM ('DIMENSIONAL', 'MATERIAL', 'PERFORMANCE', 'RELIABILITY', 'ENVIRONMENTAL', 'SAFETY', 'EMC');

-- CreateEnum
CREATE TYPE "TestResult" AS ENUM ('NOT_TESTED', 'PASS', 'FAIL', 'CONDITIONAL');

-- CreateEnum
CREATE TYPE "SampleInspectionResult" AS ENUM ('PENDING', 'PASS', 'FAIL', 'CONDITIONAL');

-- CreateEnum
CREATE TYPE "SampleStatus" AS ENUM ('REGISTERED', 'INSPECTING', 'COMPLETED', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "ComplaintType" AS ENUM ('QUALITY', 'DELIVERY', 'PACKAGING', 'DOCUMENTATION', 'SERVICE', 'OTHER');

-- CreateEnum
CREATE TYPE "ComplaintSeverity" AS ENUM ('CRITICAL', 'MAJOR', 'MINOR');

-- CreateEnum
CREATE TYPE "ComplaintStatus" AS ENUM ('RECEIVED', 'INVESTIGATING', 'RESOLVED', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "WarrantyStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'CLAIMED', 'VOIDED');

-- CreateEnum
CREATE TYPE "TraceabilityStatus" AS ENUM ('UNTRACED', 'PARTIALLY_TRACED', 'FULLY_TRACED');

-- CreateEnum
CREATE TYPE "RecallRiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "RecallStatus" AS ENUM ('PLANNED', 'INITIATED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "RecallLotStatus" AS ENUM ('IDENTIFIED', 'NOTIFIED', 'RETURNING', 'RETURNED', 'COMPLETED');

-- CreateEnum
CREATE TYPE "CapaType" AS ENUM ('CORRECTIVE', 'PREVENTIVE', 'BOTH');

-- CreateEnum
CREATE TYPE "CapaPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "CapaStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'VERIFICATION', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "EffectivenessResult" AS ENUM ('EFFECTIVE', 'PARTIALLY_EFFECTIVE', 'NOT_EFFECTIVE', 'PENDING');

-- CreateEnum
CREATE TYPE "CertificateType" AS ENUM ('COA', 'COC', 'COT', 'MILL_CERT');

-- CreateEnum
CREATE TYPE "CertificateStatus" AS ENUM ('DRAFT', 'ISSUED', 'REISSUED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "EquipmentStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'CALIBRATING', 'OUT_OF_SERVICE', 'DISPOSED');

-- CreateEnum
CREATE TYPE "CalibrationType" AS ENUM ('INTERNAL', 'EXTERNAL');

-- CreateEnum
CREATE TYPE "CalibrationResult" AS ENUM ('PASS', 'FAIL', 'ADJUSTED');

-- CreateEnum
CREATE TYPE "TraceType" AS ENUM ('FORWARD', 'BACKWARD', 'FULL');

-- CreateEnum
CREATE TYPE "EvalGrade" AS ENUM ('A', 'B', 'C', 'D', 'F');

-- CreateEnum
CREATE TYPE "ScarStatus" AS ENUM ('ISSUED', 'RESPONDED', 'VERIFIED', 'CLOSED', 'OVERDUE');

-- CreateEnum
CREATE TYPE "CompetencyLevel" AS ENUM ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT');

-- CreateEnum
CREATE TYPE "TrainingStatus" AS ENUM ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ChangeType" AS ENUM ('DESIGN', 'PROCESS', 'MATERIAL', 'SUPPLIER', 'SPECIFICATION', 'OTHER');

-- CreateEnum
CREATE TYPE "ChangeStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'REVIEWING', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'CLOSED');

-- CreateTable
CREATE TABLE "QMS_INSPECTION_LOT" (
    "LOT_NO" VARCHAR(50) NOT NULL,
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "INSPECTION_TYPE" "InspectionType" NOT NULL,
    "INSPECTION_DATE" TIMESTAMP(3),
    "INSPECTOR" VARCHAR(100),
    "LOT_QTY" INTEGER NOT NULL DEFAULT 0,
    "SAMPLE_QTY" INTEGER NOT NULL DEFAULT 0,
    "JUDGMENT" "InspectionJudgment",
    "STATUS" "InspectionStatus" NOT NULL DEFAULT 'PENDING',
    "SUPPLIER_CODE" VARCHAR(50),
    "SUPPLIER_NAME" VARCHAR(200),
    "PO_NO" VARCHAR(50),
    "WORK_ORDER_NO" VARCHAR(50),
    "REMARKS" VARCHAR(2000),
    "NCR_NO" VARCHAR(50),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_INSPECTION_LOT_pkey" PRIMARY KEY ("LOT_NO")
);

-- CreateTable
CREATE TABLE "QMS_INSPECTION_RESULT" (
    "RESULT_ID" VARCHAR(50) NOT NULL,
    "LOT_NO" VARCHAR(50) NOT NULL,
    "CHARACTERISTIC_NAME" VARCHAR(200) NOT NULL,
    "CHARACTERISTIC_NO" VARCHAR(50),
    "SPEC_MIN" DECIMAL(18,6),
    "SPEC_MAX" DECIMAL(18,6),
    "SPEC_TEXT" VARCHAR(500),
    "MEASURED_VALUE" DECIMAL(18,6),
    "MEASURED_TEXT" VARCHAR(500),
    "JUDGMENT" "ResultJudgment",
    "INSPECTION_METHOD" VARCHAR(200),
    "INSPECTION_EQUIPMENT" VARCHAR(200),
    "REMARKS" VARCHAR(2000),
    "SEQUENCE_NO" INTEGER NOT NULL DEFAULT 1,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_INSPECTION_RESULT_pkey" PRIMARY KEY ("RESULT_ID")
);

-- CreateTable
CREATE TABLE "QMS_NCR" (
    "NCR_NO" VARCHAR(50) NOT NULL,
    "TITLE" VARCHAR(500) NOT NULL,
    "DESCRIPTION" VARCHAR(4000),
    "OCCURRENCE_DATE" TIMESTAMP(3),
    "LOT_NO" VARCHAR(50),
    "ITEM_CODE" VARCHAR(50),
    "ITEM_NAME" VARCHAR(200),
    "DEFECT_QTY" INTEGER NOT NULL DEFAULT 0,
    "DEFECT_TYPE" "DefectType",
    "STATUS" "NcrStatus" NOT NULL DEFAULT 'DRAFT',
    "SOURCE" "NcrSource",
    "REPORTED_BY" VARCHAR(100),
    "REPORTED_DATE" TIMESTAMP(3),
    "ASSIGNED_TO" VARCHAR(100),
    "DUE_DATE" TIMESTAMP(3),
    "ROOT_CAUSE" VARCHAR(4000),
    "CORRECTIVE_ACTION" VARCHAR(4000),
    "PREVENTIVE_ACTION" VARCHAR(4000),
    "CLOSED_DATE" TIMESTAMP(3),
    "CLOSED_BY" VARCHAR(100),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_NCR_pkey" PRIMARY KEY ("NCR_NO")
);

-- CreateTable
CREATE TABLE "QMS_MRB_REVIEW" (
    "REVIEW_ID" VARCHAR(50) NOT NULL,
    "NCR_NO" VARCHAR(50) NOT NULL,
    "REVIEWED_BY" VARCHAR(100) NOT NULL,
    "REVIEW_DATE" TIMESTAMP(3) NOT NULL,
    "DISPOSITION" "DispositionType",
    "REASON" VARCHAR(4000),
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP(3),
    "STATUS" "ReviewStatus" NOT NULL DEFAULT 'PENDING',
    "EXECUTION_DATE" TIMESTAMP(3),
    "EXECUTION_RESULT" VARCHAR(2000),
    "EXECUTED_BY" VARCHAR(100),
    "ATTACHMENTS" VARCHAR(4000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_MRB_REVIEW_pkey" PRIMARY KEY ("REVIEW_ID")
);

-- CreateTable
CREATE TABLE "QMS_APQP_PROJECT" (
    "PROJECT_NO" VARCHAR(50) NOT NULL,
    "PROJECT_NAME" VARCHAR(200) NOT NULL,
    "CUSTOMER_CODE" VARCHAR(50),
    "CUSTOMER_NAME" VARCHAR(200),
    "ITEM_CODE" VARCHAR(50),
    "ITEM_NAME" VARCHAR(200),
    "PLANNED_START_DATE" TIMESTAMP(3),
    "PLANNED_END_DATE" TIMESTAMP(3),
    "ACTUAL_START_DATE" TIMESTAMP(3),
    "ACTUAL_END_DATE" TIMESTAMP(3),
    "PROJECT_MANAGER" VARCHAR(100),
    "STATUS" "ApqpProjectStatus" NOT NULL DEFAULT 'PLANNING',
    "TARGET_QUALITY_LEVEL" DECIMAL(5,2) DEFAULT 99.0,
    "ACTUAL_QUALITY_LEVEL" DECIMAL(5,2),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_APQP_PROJECT_pkey" PRIMARY KEY ("PROJECT_NO")
);

-- CreateTable
CREATE TABLE "QMS_APQP_PHASE" (
    "PHASE_ID" VARCHAR(50) NOT NULL,
    "PROJECT_NO" VARCHAR(50) NOT NULL,
    "PHASE_TYPE" "ApqpPhaseType" NOT NULL,
    "PHASE_NAME" VARCHAR(200) NOT NULL,
    "SEQUENCE_NO" INTEGER NOT NULL DEFAULT 1,
    "PLANNED_START_DATE" TIMESTAMP(3),
    "PLANNED_END_DATE" TIMESTAMP(3),
    "ACTUAL_START_DATE" TIMESTAMP(3),
    "ACTUAL_END_DATE" TIMESTAMP(3),
    "TARGET_QUALITY_LEVEL" DECIMAL(5,2),
    "ACTUAL_QUALITY_LEVEL" DECIMAL(5,2),
    "STATUS" "ApqpPhaseStatus" NOT NULL DEFAULT 'NOT_STARTED',
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP(3),
    "REJECTION_REASON" VARCHAR(2000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_APQP_PHASE_pkey" PRIMARY KEY ("PHASE_ID")
);

-- CreateTable
CREATE TABLE "QMS_GATE_DELIVERABLE" (
    "DELIVERABLE_ID" VARCHAR(50) NOT NULL,
    "PHASE_ID" VARCHAR(50) NOT NULL,
    "DELIVERABLE_NAME" VARCHAR(200) NOT NULL,
    "DELIVERABLE_CODE" VARCHAR(50),
    "IS_REQUIRED" BOOLEAN NOT NULL DEFAULT true,
    "IS_SUBMITTED" BOOLEAN NOT NULL DEFAULT false,
    "SUBMITTED_DATE" TIMESTAMP(3),
    "SUBMITTED_BY" VARCHAR(100),
    "STATUS" "DeliverableStatus" NOT NULL DEFAULT 'NOT_SUBMITTED',
    "APPROVED_DATE" TIMESTAMP(3),
    "APPROVED_BY" VARCHAR(100),
    "DOCUMENT_PATH" VARCHAR(500),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_GATE_DELIVERABLE_pkey" PRIMARY KEY ("DELIVERABLE_ID")
);

-- CreateTable
CREATE TABLE "QMS_PPAP_SUBMISSION" (
    "SUBMISSION_ID" VARCHAR(50) NOT NULL,
    "PROJECT_NO" VARCHAR(50) NOT NULL,
    "SUBMISSION_NO" VARCHAR(50) NOT NULL,
    "SUBMISSION_LEVEL" INTEGER NOT NULL DEFAULT 3,
    "SUBMISSION_DATE" TIMESTAMP(3),
    "CUSTOMER_CODE" VARCHAR(50),
    "CUSTOMER_NAME" VARCHAR(200),
    "STATUS" "PpapStatus" NOT NULL DEFAULT 'NOT_SUBMITTED',
    "PSW_NO" VARCHAR(50),
    "PSW_PATH" VARCHAR(500),
    "REVIEWED_BY" VARCHAR(100),
    "REVIEW_DATE" TIMESTAMP(3),
    "REJECTION_REASON" VARCHAR(2000),
    "RESUBMISSION_DATE" TIMESTAMP(3),
    "RESUBMISSION_COUNT" INTEGER NOT NULL DEFAULT 0,
    "APPROVAL_DEADLINE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_PPAP_SUBMISSION_pkey" PRIMARY KEY ("SUBMISSION_ID")
);

-- CreateTable
CREATE TABLE "QMS_PPAP_DOCUMENT" (
    "DOCUMENT_ID" VARCHAR(50) NOT NULL,
    "SUBMISSION_ID" VARCHAR(50) NOT NULL,
    "DOCUMENT_TYPE" "PpapDocumentType" NOT NULL,
    "DOCUMENT_NAME" VARCHAR(200) NOT NULL,
    "DOCUMENT_CODE" VARCHAR(50),
    "IS_REQUIRED" BOOLEAN NOT NULL DEFAULT true,
    "IS_SUBMITTED" BOOLEAN NOT NULL DEFAULT false,
    "SUBMITTED_DATE" TIMESTAMP(3),
    "STATUS" "DocumentStatus" NOT NULL DEFAULT 'NOT_SUBMITTED',
    "DOCUMENT_PATH" VARCHAR(500),
    "VERSION" VARCHAR(20),
    "REVIEWED_BY" VARCHAR(100),
    "REVIEW_DATE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_PPAP_DOCUMENT_pkey" PRIMARY KEY ("DOCUMENT_ID")
);

-- CreateTable
CREATE TABLE "QMS_PPAP_APPROVAL_HISTORY" (
    "HISTORY_ID" VARCHAR(50) NOT NULL,
    "SUBMISSION_ID" VARCHAR(50) NOT NULL,
    "ACTION" "ApprovalAction" NOT NULL,
    "ACTION_DATE" TIMESTAMP(3) NOT NULL,
    "ACTION_BY" VARCHAR(100) NOT NULL,
    "REASON" VARCHAR(2000),
    "PREVIOUS_STATUS" VARCHAR(50),
    "NEW_STATUS" VARCHAR(50) NOT NULL,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_PPAP_APPROVAL_HISTORY_pkey" PRIMARY KEY ("HISTORY_ID")
);

-- CreateTable
CREATE TABLE "QMS_DVP_PLAN" (
    "PLAN_ID" VARCHAR(50) NOT NULL,
    "PROJECT_NO" VARCHAR(50) NOT NULL,
    "ITEM_CODE" VARCHAR(50),
    "ITEM_NAME" VARCHAR(200),
    "TEST_CATEGORY" "TestCategory" NOT NULL,
    "TEST_ITEM" VARCHAR(200) NOT NULL,
    "TEST_METHOD" VARCHAR(200),
    "ACCEPTANCE_CRITERIA" VARCHAR(500),
    "TEST_FACILITY" VARCHAR(200),
    "TEST_EQUIPMENT" VARCHAR(200),
    "PLANNED_START_DATE" TIMESTAMP(3),
    "PLANNED_END_DATE" TIMESTAMP(3),
    "SAMPLE_QTY" INTEGER DEFAULT 5,
    "RESPONSIBLE_PERSON" VARCHAR(100),
    "REFERENCE_SPEC" VARCHAR(200),
    "PRIORITY" INTEGER DEFAULT 1,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_DVP_PLAN_pkey" PRIMARY KEY ("PLAN_ID")
);

-- CreateTable
CREATE TABLE "QMS_DVP_RESULT" (
    "RESULT_ID" VARCHAR(50) NOT NULL,
    "PLAN_ID" VARCHAR(50) NOT NULL,
    "ACTUAL_START_DATE" TIMESTAMP(3),
    "ACTUAL_END_DATE" TIMESTAMP(3),
    "TESTED_QTY" INTEGER DEFAULT 0,
    "PASSED_QTY" INTEGER DEFAULT 0,
    "FAILED_QTY" INTEGER DEFAULT 0,
    "TEST_RESULT" "TestResult" NOT NULL DEFAULT 'NOT_TESTED',
    "TEST_REPORT_NO" VARCHAR(50),
    "TEST_REPORT_PATH" VARCHAR(500),
    "TESTED_BY" VARCHAR(100),
    "MEASURED_VALUES" VARCHAR(4000),
    "DEFECT_DESCRIPTION" VARCHAR(2000),
    "CORRECTIVE_ACTION" VARCHAR(2000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_DVP_RESULT_pkey" PRIMARY KEY ("RESULT_ID")
);

-- CreateTable
CREATE TABLE "QMS_INITIAL_SAMPLE" (
    "SAMPLE_ID" VARCHAR(50) NOT NULL,
    "PROJECT_NO" VARCHAR(50) NOT NULL,
    "SAMPLE_NO" VARCHAR(50) NOT NULL,
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "SAMPLE_QTY" INTEGER NOT NULL DEFAULT 1,
    "SUBMISSION_DATE" TIMESTAMP(3) NOT NULL,
    "INSPECTOR" VARCHAR(100),
    "INSPECTION_RESULT" "SampleInspectionResult" NOT NULL DEFAULT 'PENDING',
    "STATUS" "SampleStatus" NOT NULL DEFAULT 'REGISTERED',
    "INSPECTION_DATE" TIMESTAMP(3),
    "APPROVAL_DATE" TIMESTAMP(3),
    "APPROVED_BY" VARCHAR(100),
    "REJECTION_REASON" VARCHAR(2000),
    "DIMENSIONAL_REPORT_NO" VARCHAR(50),
    "MATERIAL_REPORT_NO" VARCHAR(50),
    "PERFORMANCE_REPORT_NO" VARCHAR(50),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_INITIAL_SAMPLE_pkey" PRIMARY KEY ("SAMPLE_ID")
);

-- CreateTable
CREATE TABLE "QMS_SAMPLE_INSPECTION_ITEM" (
    "ITEM_ID" VARCHAR(50) NOT NULL,
    "SAMPLE_ID" VARCHAR(50) NOT NULL,
    "INSPECTION_ITEM" VARCHAR(200) NOT NULL,
    "INSPECTION_ITEM_CODE" VARCHAR(50),
    "SPEC_MIN" DECIMAL(18,6),
    "SPEC_MAX" DECIMAL(18,6),
    "SPEC_NOMINAL" DECIMAL(18,6),
    "SPEC_TOLERANCE" DECIMAL(18,6),
    "UNIT" VARCHAR(20),
    "MEASURED_VALUE" DECIMAL(18,6),
    "MEASURED_VALUES" VARCHAR(4000),
    "JUDGMENT" "SampleInspectionResult" NOT NULL DEFAULT 'PENDING',
    "IS_CRITICAL" BOOLEAN NOT NULL DEFAULT false,
    "INSPECTION_METHOD" VARCHAR(200),
    "INSPECTION_EQUIPMENT" VARCHAR(200),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_SAMPLE_INSPECTION_ITEM_pkey" PRIMARY KEY ("ITEM_ID")
);

-- CreateTable
CREATE TABLE "QMS_CUSTOMER_COMPLAINT" (
    "COMPLAINT_ID" VARCHAR(50) NOT NULL,
    "COMPLAINT_NO" VARCHAR(50) NOT NULL,
    "CUSTOMER_CODE" VARCHAR(50) NOT NULL,
    "CUSTOMER_NAME" VARCHAR(200),
    "ITEM_CODE" VARCHAR(50),
    "ITEM_NAME" VARCHAR(200),
    "OCCURRENCE_DATE" TIMESTAMP(3),
    "RECEIPT_DATE" TIMESTAMP(3) NOT NULL,
    "COMPLAINT_TYPE" "ComplaintType" NOT NULL DEFAULT 'QUALITY',
    "SEVERITY" "ComplaintSeverity",
    "DESCRIPTION" VARCHAR(4000) NOT NULL,
    "DEFECT_QTY" INTEGER NOT NULL DEFAULT 0,
    "LOT_NO" VARCHAR(50),
    "STATUS" "ComplaintStatus" NOT NULL DEFAULT 'RECEIVED',
    "RESOLUTION" VARCHAR(4000),
    "RESOLVED_DATE" TIMESTAMP(3),
    "RESOLVED_BY" VARCHAR(100),
    "RESPONSE_TIME_HOURS" INTEGER,
    "SATISFACTION_SCORE" INTEGER,
    "REPORTED_BY" VARCHAR(100),
    "ASSIGNED_TO" VARCHAR(100),
    "CLOSED_DATE" TIMESTAMP(3),
    "CLOSED_BY" VARCHAR(100),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_CUSTOMER_COMPLAINT_pkey" PRIMARY KEY ("COMPLAINT_ID")
);

-- CreateTable
CREATE TABLE "QMS_WARRANTY_RECORD" (
    "WARRANTY_ID" VARCHAR(50) NOT NULL,
    "WARRANTY_NO" VARCHAR(50) NOT NULL,
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "SERIAL_NO" VARCHAR(100),
    "SALE_DATE" TIMESTAMP(3) NOT NULL,
    "WARRANTY_PERIOD_MONTHS" INTEGER NOT NULL DEFAULT 12,
    "WARRANTY_EXPIRY_DATE" TIMESTAMP(3) NOT NULL,
    "CUSTOMER_CODE" VARCHAR(50) NOT NULL,
    "CUSTOMER_NAME" VARCHAR(200),
    "SALES_ORDER_NO" VARCHAR(50),
    "INVOICE_NO" VARCHAR(50),
    "STATUS" "WarrantyStatus" NOT NULL DEFAULT 'ACTIVE',
    "CLAIM_DATE" TIMESTAMP(3),
    "FAILURE_DATE" TIMESTAMP(3),
    "FAILURE_DESCRIPTION" VARCHAR(4000),
    "FAILURE_PART" VARCHAR(200),
    "FAILURE_CAUSE" VARCHAR(2000),
    "REPAIR_COST" DECIMAL(18,2),
    "REPLACEMENT_COST" DECIMAL(18,2),
    "LABOR_COST" DECIMAL(18,2),
    "SHIPPING_COST" DECIMAL(18,2),
    "TOTAL_COST" DECIMAL(18,2),
    "CLAIM_APPROVED_BY" VARCHAR(100),
    "CLAIM_APPROVED_DATE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_WARRANTY_RECORD_pkey" PRIMARY KEY ("WARRANTY_ID")
);

-- CreateTable
CREATE TABLE "QMS_FIELD_FAILURE" (
    "FAILURE_ID" VARCHAR(50) NOT NULL,
    "FAILURE_NO" VARCHAR(50) NOT NULL,
    "COMPLAINT_ID" VARCHAR(50),
    "WARRANTY_ID" VARCHAR(50),
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "LOT_NO" VARCHAR(50),
    "SERIAL_NO" VARCHAR(100),
    "FAILURE_DATE" TIMESTAMP(3) NOT NULL,
    "DISCOVERY_DATE" TIMESTAMP(3),
    "FAILURE_MODE" VARCHAR(500) NOT NULL,
    "FAILURE_CAUSE" VARCHAR(2000),
    "FAILURE_DETAIL" VARCHAR(4000),
    "PRODUCTION_DATE" TIMESTAMP(3),
    "PRODUCTION_LINE" VARCHAR(50),
    "EQUIPMENT_ID" VARCHAR(50),
    "EQUIPMENT_NAME" VARCHAR(200),
    "OPERATOR_ID" VARCHAR(50),
    "OPERATOR_NAME" VARCHAR(100),
    "INSPECTION_LOT_NO" VARCHAR(50),
    "RAW_MATERIAL_LOT" VARCHAR(50),
    "SUPPLIER_CODE" VARCHAR(50),
    "SUPPLIER_NAME" VARCHAR(200),
    "TRACEABILITY_STATUS" "TraceabilityStatus" NOT NULL DEFAULT 'UNTRACED',
    "IMMEDIATE_ACTION" VARCHAR(2000),
    "CORRECTIVE_ACTION" VARCHAR(2000),
    "PREVENTIVE_ACTION" VARCHAR(2000),
    "ACTION_DEADLINE" TIMESTAMP(3),
    "ACTION_COMPLETED_DATE" TIMESTAMP(3),
    "ACTION_COMPLETED_BY" VARCHAR(100),
    "VERIFICATION_RESULT" VARCHAR(2000),
    "VERIFICATION_DATE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_FIELD_FAILURE_pkey" PRIMARY KEY ("FAILURE_ID")
);

-- CreateTable
CREATE TABLE "QMS_RECALL_CAMPAIGN" (
    "RECALL_ID" VARCHAR(50) NOT NULL,
    "RECALL_NO" VARCHAR(50) NOT NULL,
    "RECALL_NAME" VARCHAR(200) NOT NULL,
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "AFFECTED_LOTS" VARCHAR(4000),
    "AFFECTED_QTY" INTEGER NOT NULL DEFAULT 0,
    "REASON" VARCHAR(2000) NOT NULL,
    "RISK_LEVEL" "RecallRiskLevel" NOT NULL DEFAULT 'MEDIUM',
    "START_DATE" TIMESTAMP(3) NOT NULL,
    "TARGET_COMPLETION_DATE" TIMESTAMP(3) NOT NULL,
    "ACTUAL_COMPLETION_DATE" TIMESTAMP(3),
    "COMPLETION_RATE" DECIMAL(5,2) DEFAULT 0,
    "TARGET_QTY" INTEGER NOT NULL DEFAULT 0,
    "COMPLETED_QTY" INTEGER NOT NULL DEFAULT 0,
    "ESTIMATED_COST" DECIMAL(18,2) DEFAULT 0,
    "ACTUAL_COST" DECIMAL(18,2) DEFAULT 0,
    "TOTAL_COST" DECIMAL(18,2) DEFAULT 0,
    "STATUS" "RecallStatus" NOT NULL DEFAULT 'PLANNED',
    "NOTIFICATION_SENT" BOOLEAN NOT NULL DEFAULT false,
    "NOTIFICATION_DATE" TIMESTAMP(3),
    "REGULATORY_REPORTED" BOOLEAN NOT NULL DEFAULT false,
    "REGULATORY_REPORT_DATE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_RECALL_CAMPAIGN_pkey" PRIMARY KEY ("RECALL_ID")
);

-- CreateTable
CREATE TABLE "QMS_RECALL_LOT" (
    "RECALL_LOT_ID" VARCHAR(50) NOT NULL,
    "RECALL_ID" VARCHAR(50) NOT NULL,
    "LOT_NO" VARCHAR(50) NOT NULL,
    "QTY" INTEGER NOT NULL DEFAULT 0,
    "CUSTOMER_CODE" VARCHAR(50),
    "CUSTOMER_NAME" VARCHAR(200),
    "SHIPMENT_DATE" TIMESTAMP(3),
    "STATUS" "RecallLotStatus" NOT NULL DEFAULT 'IDENTIFIED',
    "RETURN_QTY" INTEGER,
    "COST" DECIMAL(18,2),
    "COMPLETED_DATE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_RECALL_LOT_pkey" PRIMARY KEY ("RECALL_LOT_ID")
);

-- CreateTable
CREATE TABLE "QMS_CAPA" (
    "CAPA_ID" VARCHAR(50) NOT NULL,
    "CAPA_NO" VARCHAR(50) NOT NULL,
    "CAPA_TYPE" "CapaType" NOT NULL,
    "SOURCE_TYPE" VARCHAR(50) NOT NULL,
    "SOURCE_ID" VARCHAR(50),
    "TITLE" VARCHAR(500) NOT NULL,
    "DESCRIPTION" VARCHAR(4000) NOT NULL,
    "PRIORITY" "CapaPriority" NOT NULL DEFAULT 'MEDIUM',
    "STATUS" "CapaStatus" NOT NULL DEFAULT 'OPEN',
    "REQUESTED_BY" VARCHAR(100) NOT NULL,
    "ASSIGNED_TO" VARCHAR(100),
    "DUE_DATE" TIMESTAMP(3) NOT NULL,
    "ROOT_CAUSE" VARCHAR(4000),
    "ROOT_CAUSE_METHOD" VARCHAR(200),
    "CORRECTIVE_ACTION" VARCHAR(4000),
    "PREVENTIVE_ACTION" VARCHAR(4000),
    "ACTION_COMPLETED_DATE" TIMESTAMP(3),
    "VERIFICATION_DUE_DATE" TIMESTAMP(3),
    "VERIFICATION_RESULT" VARCHAR(2000),
    "VERIFICATION_DATE" TIMESTAMP(3),
    "VERIFIED_BY" VARCHAR(100),
    "EFFECTIVENESS_CONFIRMED" BOOLEAN NOT NULL DEFAULT false,
    "RELATED_DOCUMENTS" VARCHAR(4000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_CAPA_pkey" PRIMARY KEY ("CAPA_ID")
);

-- CreateTable
CREATE TABLE "QMS_EFFECTIVENESS_CHECK" (
    "CHECK_ID" VARCHAR(50) NOT NULL,
    "CAPA_ID" VARCHAR(50) NOT NULL,
    "CHECK_NO" INTEGER NOT NULL,
    "SCHEDULED_DATE" TIMESTAMP(3) NOT NULL,
    "ACTUAL_DATE" TIMESTAMP(3),
    "CHECKED_BY" VARCHAR(100),
    "RESULT" "EffectivenessResult",
    "EVIDENCE" VARCHAR(4000),
    "RECURRENCE_FOUND" BOOLEAN NOT NULL DEFAULT false,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_EFFECTIVENESS_CHECK_pkey" PRIMARY KEY ("CHECK_ID")
);

-- CreateTable
CREATE TABLE "QMS_INSPECTION_CERTIFICATE" (
    "CERTIFICATE_ID" VARCHAR(50) NOT NULL,
    "CERTIFICATE_NO" VARCHAR(50) NOT NULL,
    "CERTIFICATE_TYPE" "CertificateType" NOT NULL DEFAULT 'COA',
    "INSPECTION_LOT_NO" VARCHAR(50) NOT NULL,
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "CUSTOMER_CODE" VARCHAR(50),
    "CUSTOMER_NAME" VARCHAR(200),
    "LOT_NO" VARCHAR(50),
    "LOT_QTY" INTEGER,
    "INSPECTION_DATE" TIMESTAMP(3) NOT NULL,
    "ISSUE_DATE" TIMESTAMP(3) NOT NULL,
    "ISSUED_BY" VARCHAR(100) NOT NULL,
    "STATUS" "CertificateStatus" NOT NULL DEFAULT 'DRAFT',
    "TEMPLATE_ID" VARCHAR(50),
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "REISSUE_REASON" VARCHAR(2000),
    "INSPECTION_SUMMARY" VARCHAR(4000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_INSPECTION_CERTIFICATE_pkey" PRIMARY KEY ("CERTIFICATE_ID")
);

-- CreateTable
CREATE TABLE "QMS_CERTIFICATE_TEMPLATE" (
    "TEMPLATE_ID" VARCHAR(50) NOT NULL,
    "TEMPLATE_NAME" VARCHAR(200) NOT NULL,
    "TEMPLATE_TYPE" "CertificateType" NOT NULL DEFAULT 'COA',
    "CUSTOMER_CODE" VARCHAR(50),
    "DESCRIPTION" VARCHAR(2000),
    "HEADER_FIELDS" VARCHAR(4000),
    "BODY_FIELDS" VARCHAR(4000),
    "FOOTER_FIELDS" VARCHAR(4000),
    "IS_DEFAULT" BOOLEAN NOT NULL DEFAULT false,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_CERTIFICATE_TEMPLATE_pkey" PRIMARY KEY ("TEMPLATE_ID")
);

-- CreateTable
CREATE TABLE "QMS_EQUIPMENT" (
    "EQUIPMENT_ID" VARCHAR(50) NOT NULL,
    "EQUIPMENT_NO" VARCHAR(50) NOT NULL,
    "EQUIPMENT_NAME" VARCHAR(200) NOT NULL,
    "EQUIPMENT_TYPE" VARCHAR(100) NOT NULL,
    "MANUFACTURER" VARCHAR(200),
    "MODEL_NO" VARCHAR(100),
    "SERIAL_NO" VARCHAR(100),
    "SPECIFICATION" VARCHAR(500),
    "LOCATION" VARCHAR(200),
    "DEPARTMENT" VARCHAR(100),
    "STATUS" "EquipmentStatus" NOT NULL DEFAULT 'ACTIVE',
    "PURCHASE_DATE" TIMESTAMP(3),
    "CALIBRATION_CYCLE" INTEGER,
    "LAST_CALIBRATION_DATE" TIMESTAMP(3),
    "NEXT_CALIBRATION_DATE" TIMESTAMP(3),
    "CALIBRATION_LAB_NAME" VARCHAR(200),
    "CALIBRATION_LAB_CERT" VARCHAR(100),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_EQUIPMENT_pkey" PRIMARY KEY ("EQUIPMENT_ID")
);

-- CreateTable
CREATE TABLE "QMS_CALIBRATION" (
    "CALIBRATION_ID" VARCHAR(50) NOT NULL,
    "EQUIPMENT_ID" VARCHAR(50) NOT NULL,
    "CALIBRATION_NO" VARCHAR(50) NOT NULL,
    "CALIBRATION_TYPE" "CalibrationType" NOT NULL DEFAULT 'EXTERNAL',
    "CALIBRATION_DATE" TIMESTAMP(3) NOT NULL,
    "CALIBRATED_BY" VARCHAR(100),
    "EXTERNAL_LAB_NAME" VARCHAR(200),
    "RESULT" "CalibrationResult" NOT NULL DEFAULT 'PASS',
    "CERTIFICATE_NO" VARCHAR(50),
    "MEASURED_VALUES" VARCHAR(4000),
    "STANDARD_VALUES" VARCHAR(4000),
    "DEVIATION" VARCHAR(2000),
    "UNCERTAINTY" VARCHAR(500),
    "NEXT_CALIBRATION_DATE" TIMESTAMP(3),
    "IS_OOT" BOOLEAN NOT NULL DEFAULT false,
    "OOT_ACTION" VARCHAR(2000),
    "AFFECTED_LOTS" VARCHAR(4000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_CALIBRATION_pkey" PRIMARY KEY ("CALIBRATION_ID")
);

-- CreateTable
CREATE TABLE "QMS_LOT_TRACE" (
    "TRACE_ID" VARCHAR(50) NOT NULL,
    "LOT_NO" VARCHAR(50) NOT NULL,
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "TRACE_TYPE" "TraceType" NOT NULL,
    "PARENT_LOT_NO" VARCHAR(50),
    "PROCESS_CODE" VARCHAR(50),
    "PROCESS_NAME" VARCHAR(200),
    "EQUIPMENT_ID" VARCHAR(50),
    "OPERATOR_ID" VARCHAR(50),
    "OPERATOR_NAME" VARCHAR(100),
    "PRODUCTION_DATE" TIMESTAMP(3),
    "PRODUCTION_LINE" VARCHAR(50),
    "SUPPLIER_CODE" VARCHAR(50),
    "CUSTOMER_CODE" VARCHAR(50),
    "SHIPMENT_NO" VARCHAR(50),
    "SHIPMENT_DATE" TIMESTAMP(3),
    "QTY" INTEGER,
    "INSPECTION_LOT_NO" VARCHAR(50),
    "INSPECTION_RESULT" VARCHAR(50),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_LOT_TRACE_pkey" PRIMARY KEY ("TRACE_ID")
);

-- CreateTable
CREATE TABLE "QMS_CUSTOMER" (
    "CUSTOMER_CODE" VARCHAR(50) NOT NULL,
    "CUSTOMER_NAME" VARCHAR(200) NOT NULL,
    "COUNTRY" VARCHAR(100),
    "ADDRESS" VARCHAR(500),
    "CONTACT_NAME" VARCHAR(100),
    "CONTACT_EMAIL" VARCHAR(200),
    "CONTACT_PHONE" VARCHAR(50),
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_CUSTOMER_pkey" PRIMARY KEY ("CUSTOMER_CODE")
);

-- CreateTable
CREATE TABLE "QMS_ITEM" (
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200) NOT NULL,
    "ITEM_TYPE" VARCHAR(50),
    "CATEGORY" VARCHAR(100),
    "UNIT" VARCHAR(20),
    "SPECIFICATION" VARCHAR(500),
    "DRAWING_NO" VARCHAR(50),
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_ITEM_pkey" PRIMARY KEY ("ITEM_CODE")
);

-- CreateTable
CREATE TABLE "QMS_PROCESS" (
    "PROCESS_CODE" VARCHAR(50) NOT NULL,
    "PROCESS_NAME" VARCHAR(200) NOT NULL,
    "PROCESS_TYPE" VARCHAR(50),
    "DESCRIPTION" VARCHAR(2000),
    "SEQUENCE_NO" INTEGER,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_PROCESS_pkey" PRIMARY KEY ("PROCESS_CODE")
);

-- CreateTable
CREATE TABLE "QMS_COMMON_CODE" (
    "CODE_GROUP" VARCHAR(50) NOT NULL,
    "CODE_VALUE" VARCHAR(50) NOT NULL,
    "CODE_NAME" VARCHAR(200) NOT NULL,
    "CODE_NAME_EN" VARCHAR(200),
    "DESCRIPTION" VARCHAR(500),
    "SORT_ORDER" INTEGER,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "PARENT_GROUP" VARCHAR(50),
    "PARENT_VALUE" VARCHAR(50),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_COMMON_CODE_pkey" PRIMARY KEY ("CODE_GROUP","CODE_VALUE")
);

-- CreateTable
CREATE TABLE "QMS_SUPPLIER_EVAL" (
    "EVALUATION_ID" VARCHAR(50) NOT NULL,
    "SUPPLIER_CODE" VARCHAR(50) NOT NULL,
    "SUPPLIER_NAME" VARCHAR(200) NOT NULL,
    "EVALUATION_PERIOD" VARCHAR(20) NOT NULL,
    "EVALUATION_DATE" TIMESTAMP(3) NOT NULL,
    "EVALUATOR" VARCHAR(100),
    "QUALITY_SCORE" DECIMAL(5,2),
    "DELIVERY_SCORE" DECIMAL(5,2),
    "PRICE_SCORE" DECIMAL(5,2),
    "SERVICE_SCORE" DECIMAL(5,2),
    "TOTAL_SCORE" DECIMAL(5,2),
    "GRADE" "EvalGrade",
    "DEFECT_RATE" DECIMAL(5,2),
    "DELIVERY_ON_TIME" DECIMAL(5,2),
    "IMPROVEMENT_PLAN" VARCHAR(4000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_SUPPLIER_EVAL_pkey" PRIMARY KEY ("EVALUATION_ID")
);

-- CreateTable
CREATE TABLE "QMS_SCAR" (
    "SCAR_ID" VARCHAR(50) NOT NULL,
    "SCAR_NO" VARCHAR(50) NOT NULL,
    "SUPPLIER_CODE" VARCHAR(50) NOT NULL,
    "SUPPLIER_NAME" VARCHAR(200) NOT NULL,
    "ISSUE_DATE" TIMESTAMP(3) NOT NULL,
    "DUE_DATE" TIMESTAMP(3) NOT NULL,
    "NCR_NO" VARCHAR(50),
    "DESCRIPTION" VARCHAR(4000) NOT NULL,
    "ROOT_CAUSE" VARCHAR(4000),
    "CORRECTIVE_ACTION" VARCHAR(4000),
    "PREVENTIVE_ACTION" VARCHAR(4000),
    "RESPONSE_DATE" TIMESTAMP(3),
    "VERIFICATION_DATE" TIMESTAMP(3),
    "VERIFIED_BY" VARCHAR(100),
    "STATUS" "ScarStatus" NOT NULL DEFAULT 'ISSUED',
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_SCAR_pkey" PRIMARY KEY ("SCAR_ID")
);

-- CreateTable
CREATE TABLE "QMS_EMPLOYEE_COMPETENCY" (
    "COMPETENCY_ID" VARCHAR(50) NOT NULL,
    "EMPLOYEE_ID" VARCHAR(50) NOT NULL,
    "EMPLOYEE_NAME" VARCHAR(100) NOT NULL,
    "DEPARTMENT" VARCHAR(100),
    "POSITION" VARCHAR(100),
    "COMPETENCY_AREA" VARCHAR(200) NOT NULL,
    "CURRENT_LEVEL" "CompetencyLevel" NOT NULL DEFAULT 'BEGINNER',
    "TARGET_LEVEL" "CompetencyLevel",
    "CERTIFICATION_NAME" VARCHAR(200),
    "CERTIFICATION_DATE" TIMESTAMP(3),
    "EXPIRY_DATE" TIMESTAMP(3),
    "ASSESSMENT_DATE" TIMESTAMP(3),
    "ASSESSED_BY" VARCHAR(100),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_EMPLOYEE_COMPETENCY_pkey" PRIMARY KEY ("COMPETENCY_ID")
);

-- CreateTable
CREATE TABLE "QMS_TRAINING_RECORD" (
    "TRAINING_ID" VARCHAR(50) NOT NULL,
    "TRAINING_NAME" VARCHAR(200) NOT NULL,
    "TRAINING_TYPE" VARCHAR(100),
    "DESCRIPTION" VARCHAR(2000),
    "INSTRUCTOR" VARCHAR(100),
    "DEPARTMENT" VARCHAR(100),
    "PLANNED_DATE" TIMESTAMP(3),
    "ACTUAL_DATE" TIMESTAMP(3),
    "DURATION_HOURS" DECIMAL(5,1),
    "ATTENDEE_COUNT" INTEGER,
    "ATTENDEES" VARCHAR(4000),
    "STATUS" "TrainingStatus" NOT NULL DEFAULT 'PLANNED',
    "EVALUATION_SCORE" DECIMAL(5,2),
    "CERTIFICATE_ISSUED" BOOLEAN NOT NULL DEFAULT false,
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_TRAINING_RECORD_pkey" PRIMARY KEY ("TRAINING_ID")
);

-- CreateTable
CREATE TABLE "QMS_CHANGE_REQUEST" (
    "CHANGE_ID" VARCHAR(50) NOT NULL,
    "CHANGE_NO" VARCHAR(50) NOT NULL,
    "CHANGE_TYPE" "ChangeType" NOT NULL,
    "TITLE" VARCHAR(500) NOT NULL,
    "DESCRIPTION" VARCHAR(4000) NOT NULL,
    "REASON" VARCHAR(2000) NOT NULL,
    "ITEM_CODE" VARCHAR(50),
    "ITEM_NAME" VARCHAR(200),
    "REQUESTED_BY" VARCHAR(100) NOT NULL,
    "REQUEST_DATE" TIMESTAMP(3) NOT NULL,
    "REVIEWED_BY" VARCHAR(100),
    "REVIEW_DATE" TIMESTAMP(3),
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP(3),
    "IMPLEMENTED_BY" VARCHAR(100),
    "IMPLEMENTED_DATE" TIMESTAMP(3),
    "STATUS" "ChangeStatus" NOT NULL DEFAULT 'DRAFT',
    "IMPACT_ASSESSMENT" VARCHAR(4000),
    "RISK_ASSESSMENT" VARCHAR(4000),
    "VALIDATION_RESULT" VARCHAR(2000),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_CHANGE_REQUEST_pkey" PRIMARY KEY ("CHANGE_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "QMS_CUSTOMER_COMPLAINT_COMPLAINT_NO_key" ON "QMS_CUSTOMER_COMPLAINT"("COMPLAINT_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_WARRANTY_RECORD_WARRANTY_NO_key" ON "QMS_WARRANTY_RECORD"("WARRANTY_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_FIELD_FAILURE_FAILURE_NO_key" ON "QMS_FIELD_FAILURE"("FAILURE_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_RECALL_CAMPAIGN_RECALL_NO_key" ON "QMS_RECALL_CAMPAIGN"("RECALL_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_CAPA_CAPA_NO_key" ON "QMS_CAPA"("CAPA_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_INSPECTION_CERTIFICATE_CERTIFICATE_NO_key" ON "QMS_INSPECTION_CERTIFICATE"("CERTIFICATE_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_EQUIPMENT_EQUIPMENT_NO_key" ON "QMS_EQUIPMENT"("EQUIPMENT_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_CALIBRATION_CALIBRATION_NO_key" ON "QMS_CALIBRATION"("CALIBRATION_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_SCAR_SCAR_NO_key" ON "QMS_SCAR"("SCAR_NO");

-- CreateIndex
CREATE UNIQUE INDEX "QMS_CHANGE_REQUEST_CHANGE_NO_key" ON "QMS_CHANGE_REQUEST"("CHANGE_NO");

-- AddForeignKey
ALTER TABLE "QMS_INSPECTION_RESULT" ADD CONSTRAINT "QMS_INSPECTION_RESULT_LOT_NO_fkey" FOREIGN KEY ("LOT_NO") REFERENCES "QMS_INSPECTION_LOT"("LOT_NO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_MRB_REVIEW" ADD CONSTRAINT "QMS_MRB_REVIEW_NCR_NO_fkey" FOREIGN KEY ("NCR_NO") REFERENCES "QMS_NCR"("NCR_NO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_APQP_PHASE" ADD CONSTRAINT "QMS_APQP_PHASE_PROJECT_NO_fkey" FOREIGN KEY ("PROJECT_NO") REFERENCES "QMS_APQP_PROJECT"("PROJECT_NO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_GATE_DELIVERABLE" ADD CONSTRAINT "QMS_GATE_DELIVERABLE_PHASE_ID_fkey" FOREIGN KEY ("PHASE_ID") REFERENCES "QMS_APQP_PHASE"("PHASE_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_PPAP_DOCUMENT" ADD CONSTRAINT "QMS_PPAP_DOCUMENT_SUBMISSION_ID_fkey" FOREIGN KEY ("SUBMISSION_ID") REFERENCES "QMS_PPAP_SUBMISSION"("SUBMISSION_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_PPAP_APPROVAL_HISTORY" ADD CONSTRAINT "QMS_PPAP_APPROVAL_HISTORY_SUBMISSION_ID_fkey" FOREIGN KEY ("SUBMISSION_ID") REFERENCES "QMS_PPAP_SUBMISSION"("SUBMISSION_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_DVP_RESULT" ADD CONSTRAINT "QMS_DVP_RESULT_PLAN_ID_fkey" FOREIGN KEY ("PLAN_ID") REFERENCES "QMS_DVP_PLAN"("PLAN_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_SAMPLE_INSPECTION_ITEM" ADD CONSTRAINT "QMS_SAMPLE_INSPECTION_ITEM_SAMPLE_ID_fkey" FOREIGN KEY ("SAMPLE_ID") REFERENCES "QMS_INITIAL_SAMPLE"("SAMPLE_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_RECALL_LOT" ADD CONSTRAINT "QMS_RECALL_LOT_RECALL_ID_fkey" FOREIGN KEY ("RECALL_ID") REFERENCES "QMS_RECALL_CAMPAIGN"("RECALL_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_EFFECTIVENESS_CHECK" ADD CONSTRAINT "QMS_EFFECTIVENESS_CHECK_CAPA_ID_fkey" FOREIGN KEY ("CAPA_ID") REFERENCES "QMS_CAPA"("CAPA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QMS_CALIBRATION" ADD CONSTRAINT "QMS_CALIBRATION_EQUIPMENT_ID_fkey" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "QMS_EQUIPMENT"("EQUIPMENT_ID") ON DELETE CASCADE ON UPDATE CASCADE;
