/**
 * @file ppap-document.entity.ts
 * @description Entity enum definitions
 */

export enum PpapDocumentType { DESIGN_RECORDS = 'DESIGN_RECORDS', DESIGN_RECORD = 'DESIGN_RECORD', ENGINEERING_CHANGE = 'ENGINEERING_CHANGE', CUSTOMER_APPROVAL = 'CUSTOMER_APPROVAL', DFMEA = 'DFMEA', FMEA = 'FMEA', PROCESS_FLOW = 'PROCESS_FLOW', PFMEA = 'PFMEA', CONTROL_PLAN = 'CONTROL_PLAN', MSA = 'MSA', DIMENSIONAL = 'DIMENSIONAL', DIMENSIONAL_RESULTS = 'DIMENSIONAL_RESULTS', MATERIAL_TEST = 'MATERIAL_TEST', MATERIAL_PERFORMANCE = 'MATERIAL_PERFORMANCE', PERFORMANCE_TEST = 'PERFORMANCE_TEST', QUALIFIED_LAB = 'QUALIFIED_LAB', QUALIFIED_LAB_DOCUMENTATION = 'QUALIFIED_LAB_DOCUMENTATION', APPEARANCE_APPROVAL = 'APPEARANCE_APPROVAL', AAR = 'AAR', SAMPLE_PRODUCT = 'SAMPLE_PRODUCT', SAMPLE_PARTS = 'SAMPLE_PARTS', MASTER_SAMPLE = 'MASTER_SAMPLE', CHECKING_AIDS = 'CHECKING_AIDS', CUSTOMER_SPECIFIC = 'CUSTOMER_SPECIFIC', PSW = 'PSW', INITIAL_PROCESS_STUDIES = 'INITIAL_PROCESS_STUDIES' }
export enum DocumentStatus { NOT_SUBMITTED = 'NOT_SUBMITTED', SUBMITTED = 'SUBMITTED', APPROVED = 'APPROVED', REJECTED = 'REJECTED' }
